const assert = require('node:assert/strict')
const path = require('node:path')
const { test } = require('node:test')
const { launch, route, settled } = require('./helpers/motion-fixture.cjs')

const navOrder = page => page.locator('#left [data-sidebar-nav]').evaluateAll(items => items.map(item => item.dataset.sidebarNav))
const waitOrder = (page, order) => page.waitForFunction(order => JSON.stringify(Array.from(document.querySelectorAll('#left [data-sidebar-nav]'), item => item.dataset.sidebarNav)) === JSON.stringify(order), order)
const widthOf = async page => (await page.locator('#left').boundingBox()).width
const dragNavigation = async(page, from, to) => {
  const source = await page.locator(`[data-sidebar-nav="${from}"]`).boundingBox()
  const target = await page.locator(`[data-sidebar-nav="${to}"]`).boundingBox()
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2)
  await page.mouse.down()
  await page.mouse.move(target.x + target.width / 2, target.y + 8, { steps: 20 })
  await page.waitForTimeout(200)
  await page.mouse.up()
}

test('sidebar resizes, reorders without navigating, preserves settings and couples download visibility to its feature switch', { timeout: 80000 }, async t => {
  let fixture = await launch({ initializeMotion: false, rendererPath: path.resolve('dist/index.html') })
  t.after(async() => { if (fixture) await fixture.app.close() })
  const { app, page, errors, output } = fixture
  page.setDefaultTimeout(10000)
  await app.evaluate(() => { global.lx.event_app.update_config({ 'download.enable': true, 'common.langId': 'zh-cn' }) })
  await waitOrder(page, ['Search', 'SongList', 'Leaderboard', 'List', 'Download', 'Setting'])
  await route(page, '/list')
  await settled(page)
  await page.locator('[data-sidebar-nav="Setting"] a').click()
  await page.waitForFunction(() => location.hash.startsWith('#/setting'))
  await page.locator('[data-sidebar-nav="List"] a').click()
  await page.waitForFunction(() => location.hash.startsWith('#/list'))

  // An ordinary drag starts after movement, without requiring a long press.
  const source = await page.locator('[data-sidebar-nav="Setting"]').boundingBox()
  const target = await page.locator('[data-sidebar-nav="Search"]').boundingBox()
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2)
  await page.mouse.down()
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2 - 12, { steps: 3 })
  await page.waitForTimeout(80)
  await page.mouse.move(target.x + target.width / 2, target.y + 8, { steps: 20 })
  await page.waitForTimeout(200)
  await page.mouse.up()
  await waitOrder(page, ['Setting', 'Search', 'SongList', 'Leaderboard', 'List', 'Download'])
  assert(page.url().includes('#/list'), 'Reordering must not activate the dragged navigation link')

  await page.locator('[data-sidebar-nav="Setting"] a').focus()
  await page.keyboard.press('Alt+ArrowDown')
  await waitOrder(page, ['Search', 'Setting', 'SongList', 'Leaderboard', 'List', 'Download'])
  await page.keyboard.press('Alt+ArrowUp')
  await waitOrder(page, ['Setting', 'Search', 'SongList', 'Leaderboard', 'List', 'Download'])
  const savedOrder = await navOrder(page)

  const separator = page.locator('[data-sidebar-resize]')
  const logo = page.locator('#left').getByText('LX-M', { exact: true })
  const logoFontSize = () => logo.evaluate(element => parseFloat(window.getComputedStyle(element).fontSize))
  const beforeWidth = await widthOf(page)
  const beforeLogoFontSize = await logoFontSize()
  const handle = await separator.boundingBox()
  await page.mouse.move(handle.x + handle.width / 2, handle.y + 140)
  await page.mouse.down()
  await page.mouse.move(handle.x + handle.width / 2 + 60, handle.y + 140, { steps: 12 })
  await page.mouse.up()
  assert(await widthOf(page) > beforeWidth + 40)
  assert(await logoFontSize() > beforeLogoFontSize, 'the logo should grow with the main sidebar')
  await separator.press('Home')
  await page.waitForFunction(() => Math.abs(document.getElementById('left').getBoundingClientRect().width - 64) < 1)
  assert(await logoFontSize() < beforeLogoFontSize, 'the logo should shrink with the main sidebar')
  assert.equal(await logo.evaluate(element => {
    const text = document.createRange()
    text.selectNodeContents(element)
    const textRect = text.getBoundingClientRect()
    const logoRect = element.getBoundingClientRect()
    return textRect.left >= logoRect.left && textRect.right <= logoRect.right && Math.abs((textRect.left + textRect.right) / 2 - (logoRect.left + logoRect.right) / 2) < 1
  }), true, 'the whole logo should remain centered at the smallest sidebar width')
  await separator.press('End')
  assert(await widthOf(page) <= 241)
  const retainedWidth = await widthOf(page)
  const resized = await separator.boundingBox()
  await page.mouse.move(resized.x + resized.width / 2, resized.y + 160)
  await page.mouse.down()
  await page.mouse.move(resized.x - 40, resized.y + 160, { steps: 8 })
  await page.keyboard.press('Escape')
  await page.mouse.up()
  assert(Math.abs(await widthOf(page) - retainedWidth) < 1, 'Escape cancels an unfinished resize')
  assert.equal(await page.locator('html').evaluate(el => el.classList.contains('sidebar-resizing')), false)
  await separator.press('Home')
  for (let i = 0; i < 10; i++) await separator.press('ArrowRight')
  await page.waitForFunction(() => document.getElementById('left').getBoundingClientRect().width >= 140)
  const savedWidth = await widthOf(page)

  const openMenu = async() => {
    await page.locator('[data-sidebar-empty]').click({ button: 'right' })
    await page.getByRole('menu', { name: '显示侧边栏按钮' }).waitFor()
  }
  const menu = page.getByRole('menu', { name: '显示侧边栏按钮' })
  await openMenu()
  assert.equal(await menu.getByRole('menuitemcheckbox').count(), 6)
  assert.equal(await menu.getByRole('menuitemcheckbox', { name: '设置', exact: true }).count(), 0)
  const names = await page.evaluate(() => ['search', 'song_list', 'leaderboard', 'my_list', 'download'].map(key => window.i18n.t(key)))
  for (const [index, name] of names.entries()) {
    if (index === 0) await page.keyboard.press('Space')
    else await menu.getByRole('menuitemcheckbox', { name, exact: true }).click()
    await page.waitForFunction(name => {
      const menu = document.querySelector('[role="menu"][aria-hidden="false"]')
      return Array.from(menu.querySelectorAll('[role="menuitemcheckbox"]')).some(button => button.textContent.trim() === name && button.getAttribute('aria-checked') === 'false' && !button.disabled)
    }, name)
    if (index === 0) assert.equal(await menu.getByRole('menuitemcheckbox', { name, exact: true }).evaluate(el => document.activeElement === el), true)
  }
  await waitOrder(page, ['Setting'])
  assert.equal(await app.evaluate(() => global.lx.appSetting['download.enable']), false)
  await page.keyboard.press('Escape')
  await page.locator('[data-sidebar-nav="Setting"] a').click()
  await route(page, '/setting?name=SettingDownload')
  await page.locator('#setting_download_enable').waitFor({ state: 'attached' })
  assert.equal(await page.locator('#setting_download_enable').isChecked(), false)
  await page.locator('label[for="setting_download_enable"]').click()
  await waitOrder(page, ['Setting', 'Download'])
  await openMenu()
  assert.equal(await menu.getByRole('menuitemcheckbox', { name: names[4], exact: true }).getAttribute('aria-checked'), 'true')
  await menu.getByRole('menuitemcheckbox', { name: names[4], exact: true }).click()
  await page.waitForFunction(() => document.getElementById('setting_download_enable').checked === false)

  // Showing hidden buttons restores their saved slots; Download stays disabled.
  for (const name of names.slice(0, 4)) await menu.getByRole('menuitemcheckbox', { name, exact: true }).click()
  await waitOrder(page, savedOrder.filter(id => id !== 'Download'))
  await menu.getByRole('menuitemcheckbox', { name: names[2], exact: true }).click()
  const visibleOrder = savedOrder.filter(id => !['Leaderboard', 'Download'].includes(id))
  await waitOrder(page, visibleOrder)
  await page.screenshot({ path: path.resolve('logs/sidebar-customization.png') })
  await page.keyboard.press('Escape')
  assert.deepEqual(errors, [])
  await app.close()
  fixture = null

  fixture = await launch({ initializeMotion: false, rendererPath: path.resolve('dist/index.html'), profilePath: output })
  await waitOrder(fixture.page, visibleOrder)
  assert(Math.abs(await widthOf(fixture.page) - savedWidth) < 1)
  assert.equal(await fixture.app.evaluate(() => global.lx.appSetting['ui.sidebar.order']), savedOrder.join(','))
  assert.equal(await fixture.app.evaluate(() => global.lx.appSetting['download.enable']), false)
  await fixture.page.locator('[data-sidebar-resize]').dblclick()
  await fixture.page.waitForFunction(() => window.lxData.appSetting['ui.sidebar.width'] === 0)
  assert(await widthOf(fixture.page) < savedWidth)
  await fixture.page.locator('[data-sidebar-empty]').click({ button: 'right' })
  await fixture.page.getByRole('menuitem', { name: '恢复默认顺序' }).click()
  await waitOrder(fixture.page, ['Search', 'SongList', 'List', 'Setting'])
  assert.equal(await fixture.app.evaluate(() => global.lx.appSetting['download.enable']), false)
  assert.deepEqual(fixture.errors, [])
})

test('sidebar lock blocks resizing and reordering, survives restart, and can be unlocked', { timeout: 60000 }, async t => {
  let fixture = await launch({ rendererPath: path.resolve('dist/index.html') })
  t.after(async() => { if (fixture) await fixture.app.close() })
  const { page, app, output } = fixture
  page.setDefaultTimeout(5000)
  const defaultOrder = ['Search', 'SongList', 'Leaderboard', 'List', 'Download', 'Setting']
  await app.evaluate(() => { global.lx.event_app.update_config({ 'download.enable': true, 'common.langId': 'zh-cn' }) })
  await waitOrder(page, defaultOrder)
  await route(page, '/setting')
  await settled(page)
  const separator = page.locator('[data-sidebar-resize]')
  await separator.press('Home')
  for (let index = 0; index < 5; index++) await separator.press('ArrowRight')
  const savedWidth = await widthOf(page)
  const edge = await separator.boundingBox()
  await page.locator('[data-sidebar-nav="Setting"] a').press('Alt+ArrowUp')
  const savedOrder = ['Search', 'SongList', 'Leaderboard', 'List', 'Setting', 'Download']
  await waitOrder(page, savedOrder)
  const openMenu = async page => {
    await page.locator('[data-sidebar-empty]').click({ button: 'right' })
    const menu = page.getByRole('menu', { name: '显示侧边栏按钮' })
    await menu.waitFor()
    return menu
  }
  const menu = await openMenu(page)
  const lock = menu.getByRole('menuitemcheckbox', { name: '锁定', exact: true })
  assert.equal(await lock.getAttribute('aria-checked'), 'false')
  await lock.click()
  await page.waitForFunction(() => window.lxData.appSetting['ui.sidebar.locked'] === true)
  assert.equal(await lock.getAttribute('aria-checked'), 'true')
  assert.equal(await menu.getByRole('menuitem', { name: '恢复默认宽度' }).isDisabled(), true)
  assert.equal(await menu.getByRole('menuitem', { name: '恢复默认顺序' }).isDisabled(), true)
  await page.screenshot({ path: path.resolve('logs/sidebar-locked.png') })
  await page.keyboard.press('Escape')
  assert.equal(await separator.count(), 0)
  await page.mouse.move(edge.x + edge.width / 2, edge.y + 160)
  await page.mouse.down()
  await page.mouse.move(edge.x + edge.width / 2 + 80, edge.y + 160, { steps: 12 })
  await page.mouse.up()
  await page.mouse.dblclick(edge.x + edge.width / 2, edge.y + 160)
  await page.locator('#left').focus()
  await page.keyboard.press('Home')
  await page.keyboard.press('End')
  assert.equal(await widthOf(page), savedWidth)
  await page.locator('[data-sidebar-nav="Setting"] a').press('Alt+ArrowUp')
  assert.deepEqual(await navOrder(page), savedOrder)
  await dragNavigation(page, 'Setting', 'Search')
  assert.deepEqual(await navOrder(page), savedOrder)
  await page.locator('[data-sidebar-nav="List"] a').click()
  await page.waitForFunction(() => location.hash.startsWith('#/list'))
  assert.deepEqual(fixture.errors, [])
  fixture = null
  await app.close()

  fixture = await launch({ rendererPath: path.resolve('dist/index.html'), profilePath: output })
  const restoredPage = fixture.page
  await waitOrder(restoredPage, savedOrder)
  assert.equal(await fixture.app.evaluate(() => global.lx.appSetting['ui.sidebar.locked']), true)
  assert.equal(await widthOf(restoredPage), savedWidth)
  assert.equal(await restoredPage.locator('[data-sidebar-resize]').count(), 0)
  const restoredMenu = await openMenu(restoredPage)
  const restoredLock = restoredMenu.getByRole('menuitemcheckbox', { name: '锁定', exact: true })
  assert.equal(await restoredLock.getAttribute('aria-checked'), 'true')
  await restoredLock.press('Space')
  await restoredPage.waitForFunction(() => window.lxData.appSetting['ui.sidebar.locked'] === false)
  assert.equal(await restoredMenu.getByRole('menuitem', { name: '恢复默认宽度' }).isEnabled(), true)
  assert.equal(await restoredMenu.getByRole('menuitem', { name: '恢复默认顺序' }).isEnabled(), true)
  await restoredPage.keyboard.press('Escape')
  const restoredSeparator = restoredPage.locator('[data-sidebar-resize]')
  await restoredSeparator.press('Home')
  await restoredPage.waitForFunction(() => document.getElementById('left').getBoundingClientRect().width === 64)
  await restoredSeparator.press('ArrowRight')
  await restoredPage.waitForFunction(() => document.getElementById('left').getBoundingClientRect().width === 72)
  await dragNavigation(restoredPage, 'Setting', 'Search')
  await waitOrder(restoredPage, ['Setting', 'Search', 'SongList', 'Leaderboard', 'List', 'Download'])
  await openMenu(restoredPage)
  await restoredMenu.getByRole('menuitem', { name: '恢复默认顺序' }).click()
  await waitOrder(restoredPage, defaultOrder)

  // A setting update can arrive while the resize handle still has pointer capture.
  const beforeCancel = await widthOf(restoredPage)
  const handle = await restoredSeparator.boundingBox()
  await restoredPage.mouse.move(handle.x + handle.width / 2, handle.y + 160)
  await restoredPage.mouse.down()
  await restoredPage.mouse.move(handle.x + handle.width / 2 + 50, handle.y + 160, { steps: 8 })
  assert(await widthOf(restoredPage) > beforeCancel)
  await fixture.app.evaluate(() => { global.lx.event_app.update_config({ 'ui.sidebar.locked': true }) })
  await restoredPage.waitForFunction(() => window.lxData.appSetting['ui.sidebar.locked'] === true)
  await restoredPage.mouse.up()
  assert.equal(await widthOf(restoredPage), beforeCancel)
  assert.equal(await restoredPage.locator('html').evaluate(element => element.classList.contains('sidebar-resizing')), false)
  assert.deepEqual(fixture.errors, [])
})
